name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your code
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      # Step 3: Install dependencies & build your site
      - name: Install & Build
        run: |
          npm install
          npm run build

      # Step 4: Deploy to your server (via SCP)
      - name: Upload Files via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "./public/*"
          target: "/var/www/msrepsitetest"